[package]
name = "system_tray"
version = "0.1.0"
edition = "2021"

[dependencies]
muda = { git = "https://github.com/amrbashir/muda", branch = "rewrite" }
crossbeam-channel = "0.5"
once_cell = "1"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.42"
features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"]


[target."cfg(target_os = \"linux\")".dependencies]
gdk-pixbuf = { version = "0.15", features = ["v2_36_8"] }

[target."cfg(target_os = \"macos\")".dependencies]
objc = "0.2"

[target."cfg(any(target_os = \"linux\", target_os = \"macos\"))".dependencies]
png = "0.17"

[dev-dependencies]
winit = "0.27"
tao = { git = "https://github.com/tauri-apps/tao", branch = "muda" }
image = "0.24"
